---
title: "Clinical trials in Finland"
date: "`r paste0('Updated: ', Sys.Date())`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: spacelab  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(flexdashboard)
library(DT)


# Download dataset and wrangle
library(httr)
library(jsonlite)
library(tibble)
library(dplyr)

if(TRUE){
  min_rnk=1
  max_rnk=100
  i=1
  more_studies=TRUE
  base_url <- readLines("base_url.txt")
  trials_final <- dplyr::tibble()
  ## Start data gathering
  while (more_studies) {
    ## Get data
    message(paste0("Downloading dataset ",i, " // ", Sys.time()))
    url <- paste0(base_url, "&min_rnk=", min_rnk,"&max_rnk=", max_rnk,"&fmt=json")
    res <- fromJSON(content(GET(url)))
    df <- as_tibble(res$FullStudiesResponse$FullStudies)
    ## Get more studies
    if(nrow(df) == 100){
      min_rnk = min_rnk + 100
      max_rnk = max_rnk + 100
      i = i + 1
    }else{
      more_studies <- FALSE
    }
    ## Join data
    if(nrow(trials_final) <= 0){
      trials_final <- df
    }else{
      trials_final <- trials_final %>% 
        bind_rows(df)
    }
  }
  ## Save dataset
  # message(paste0("Saving full dataset. Found ", nrow(trials_final), " trials // ", Sys.time()))
  # saveRDS(trials_final, file = paste0("./data/temp_trials.rds"))
  
  ## Create Final data & URL link
  df <- trials_final
  df$url <- paste0("trials/", df$Study$ProtocolSection$IdentificationModule$NCTId, ".html")
  df$Link <- paste0("<a href='",df$url,"'>Description</a>")
  
  rm(list = c("trials_final", "res", "url", "min_rnk", "max_rnk","more_studies", "i"))
}




dat <- dplyr::tibble(
    Status = as.factor(df$Study$ProtocolSection$StatusModule$OverallStatus),
    Title = df$Study$ProtocolSection$IdentificationModule$BriefTitle, 
    Organization = df$Study$ProtocolSection$IdentificationModule$Organization$OrgFullName, 
    Started = df$Study$ProtocolSection$StatusModule$StartDateStruct$StartDate,
    # LastStatus = df$Study$ProtocolSection$StatusModule$LastKnownStatus,
    Condition = rapply((df$Study$ProtocolSection$ConditionsModule$ConditionList$Condition), paste0, collapse = ", "),
    Keyword = rapply(as.list(stringr::str_replace(string = df$Study$ProtocolSection$ConditionsModule$KeywordList$Keyword, 
                                                  pattern = "NULL", 
                                                  replacement = "")), 
                     paste0, collapse = ", "),
    # as.list(stringr::str_replace((df$Study$ProtocolSection$ConditionsModule$KeywordList$Keyword), "NULL", ""))
    Link = df$Link
  )
```


Info
=======================================================================

Row
-----------------------------------------------------------------------

### Trials

```{r}
valueBox(nrow(dat), icon = "fa-medkit")
```

### Organizations

```{r}
valueBox(length(unique(df$Study$ProtocolSection$IdentificationModule$Organization$OrgFullName)), icon = "fa-sitemap")
```

### Sponsors

```{r}
valueBox(length(unique(df$Study$ProtocolSection$SponsorCollaboratorsModule$LeadSponsor$LeadSponsorName)), icon = "fa-user")
```


<!-- ### example&&&&&Subjects -->

<!-- ```{r} -->
<!-- valueBox(22222, icon = "fa-users") -->
<!-- ``` -->

Row
-----------------------------------------------------------------------


```{r datatable}
DT::datatable(dat,
              selection = c("single"),
              rownames = FALSE, 
              filter = 'top',
              escape = FALSE,
              #extensions = 'Buttons', 
              options = list(
                order = list(list(0, 'desc'), list(2, 'asc')),
                # dom = 'Bfrtip',
                search = list(regex = TRUE, caseInsensitive = TRUE),
                columnDefs = list(list(className = 'dt-left',  targets = "_all")),
                pageLength = 20
                # language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Finnish.json')
                # dom = 'Bfrtip',
                # buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
              ))%>%
  formatStyle(
    'Status',
    backgroundColor = styleEqual(levels = c("Not yet recruiting", "Recruiting", "Active, not recruiting"), values = c("yellow", "green", "orange"))
  ) 
```

About
=======================================================================

### About this webpage

We collected information of clinical trials which are currently held in Finland. Data is obtained from [ClinicalTrials.gov](https://clinicaltrials.gov/) and it is parsed, cleaned and formatted for user readable form. Check data [Terms and Conditions](https://clinicaltrials.gov/ct2/about-site/terms-conditions). In case of a question, please [contact us]().

